CI validate against fortran
ai2cm/pace pull request #280
Opened 2022-08-17 16:18 UTC by elynnwu

## Purpose

Describe the purpose of this PR and the motivation if relevant to understanding. Include links to related issues, bugs or features.

Remove the sections below which do not apply.

## Code changes:

- Provide a list of relevant code changes and the side effects they have on other code.

## Requirements changes:

- Provide a list of any changes made to requirements, e.g. changes to files requirements*.txt, constraints.txt, setup.py, pyproject.toml, pre-commit-config.yaml and a reason if not included in the Purpose section (e.g. incompatibility, updates, etc)

## Infrastructure changes:

- Provide a list of changes that impact the infrastructure around running the code -- that is, changes to Makefiles, docker files, git submodules, or .jenkins (testing infrastructure changes). If Jenkins plans are also being manually changed, indicate that as well.

## Checklist
Before submitting this PR, please make sure:

- [ ] You have followed the coding standards guidelines established at [Code Review Checklist](https://drive.google.com/file/d/1R0nqOxfYnzaSdoYdt8yjx5J482ETI2Ft/view?usp=sharing).
- [ ] Docstrings and type hints are added to new and updated routines, as appropriate
- [ ] All relevant documentation has been updated or added (e.g. README, CONTRIBUTING docs)
- [ ] For each public change and fix in `pace-util`, HISTORY has been updated
- [ ] Unit tests are added or updated for non-stencil code changes

Additionally, if this PR contains code authored by new contributors:

- [ ] The names of all the new contributors have been added to CONTRIBUTORS.md

2022-08-19 22:25 UTC, elynnwu commented on driver/pace/driver/initialization.py
> +            compilation_config=CompilationConfig(backend=backend),
Will probably revert this since Tobias has a more thorough fix in his branch

2022-08-19 22:27 UTC, elynnwu commented on driver/examples/plot_pcolormesh_cube.py
> +                args.fortran_data_path, args.size, args.fortran_var, args.zlevel, 20
We hard code this to 20 because we only have one set of wrapper data in this format for now. Will add longer runs later.

2022-08-22 23:37 UTC, twicki requested changes

2022-08-22 23:37 UTC, twicki commented on .jenkins/driver_configs/baroclinic_c48_6ranks_dycore_only.yaml
> +dycore_only: true
we should probably add these as files to be tested here:
https://github.com/ai2cm/pace/blob/main/tests/main/driver/test_example_configs.py

2022-08-22 23:37 UTC, twicki commented on .jenkins/driver_configs/baroclinic_c48_6ranks_dycore_only.yaml
> +# minutes: 7200
do we actually plan to update this soon?

2022-08-22 23:37 UTC, twicki commented on .jenkins/run_compare_fortran.sh
> +#!/bin/bash
can we add a usage comment?

2022-08-22 23:37 UTC, twicki commented on .jenkins/run_compare_fortran.sh
> +srun -C gpu --partition=normal --account=s1053 --time=00:30:00 sarus run --mount=type=bind,source=${PACE_DIR},destination=/work elynnwu/pace:latest python /work/driver/examples/plot_pcolormesh_cube.p
should this have s/p grid in the experiment name as well?

2022-08-23 22:38 UTC, twicki approved these changes
LGTM

2022-08-24 00:40 UTC, merged